### ISSUE TITLE
when trying to resize image (CTRL+Shift+R)

### ISSUE THREAD

**Issue by temginson** [PintaProject/Pinta#1017]
**Description**
when trying to resize image it just comes up with unhandled exception object reference not set to an instance of an object 

**To Reproduce**
just pressing (CTRL+Shift+R)

**Additional Info**
System.NullReferenceException: Object reference not set to an instance of an object.
   at Pinta.ResizeCanvasDialog.SetAnchor(Anchor anchor) in D:\a\Pinta\Pinta\Pinta\Dialogs\ResizeCanvasDialog.cs:line 333
   at Pinta.ResizeCanvasDialog..ctor() in D:\a\Pinta\Pinta\Pinta\Dialogs\ResizeCanvasDialog.cs:line 188
   at Pinta.Actions.ResizeCanvasAction.Activated(Object sender, EventArgs e) in D:\a\Pinta\Pinta\Pinta\Actions\Image\ResizeCanvasAction.cs:line 46
   at Pinta.Core.Command.<.ctor>b__29_0(SimpleAction o, ActivateSignalArgs args) in D:\a\Pinta\Pinta\Pinta.Core\Actions\Command.cs:line 63
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, IntPtr paramValuesData, IntPtr invocationHint, IntPtr userData)

**Version**
windows 10) and version of Pinta 2.2

**Comment by cameronwhite** [comment]
Ah sorry, I think the development builds I linked you to were out of date
This should have been fixed by 975cbd04ed713b9ea531ee48a0bb0b2554e0006d

I've updated the builds at https://github.com/PintaProject/Pinta/releases/tag/dev-preview-builds - could you download the updated build (should be `Pinta-2.2-dev2018.exe`) and try that?

**Comment by cameronwhite** [comment]
Ah sorry, there was a recent bug that caused a missing dll on Windows. Can you try again with the latest build from https://github.com/PintaProject/Pinta/releases/tag/dev-preview-builds (should be `Pinta-2.2-dev2022.exe`)

**Comment by cameronwhite** [comment]
Closing as this should have been resolved with the later fixes to the Windows installer
