### ISSUE TITLE
redo stack is empty 

### ISSUE THREAD

**Issue by temginson** [PintaProject/Pinta#536]
**Description**
A description of what the bug is.
makes the program not work

**To Reproduce**
Steps to reproduce the issue.
have a few 100 edits in the history menu and start pressing ctrl+z

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
Please include your operating system (e.g. Ubuntu 22.04) and which version of Pinta (e.g. 2.1) you are using.
Utgåva	Windows 11 Pro
Version	23H2
Installerad	‎2023-‎03-‎02
OS-version	22631.2338
Gränssnitt	Windows Feature Experience Pack 1000.22674.1000.0

pinta 2.1.1

**Comment by cameronwhite** [comment]
Thanks for the report!

Would you be able to attach the full log from when the error happens? When the error dialog appears this text should be in the contents of the `Details` tab when expanded

**Comment by temginson** [comment]
No i can not because i don't have it but next time i encounter the same bug i will do

**Comment by temginson** [comment]
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Object has already been disposed'.
   at Cairo.Surface.CheckDisposed()
   at Cairo.ImageSurface.get_Width()
   at Pinta.Gui.Widgets.CellRendererSurface.RenderCell(Context g, Int32 width, Int32 height) in D:\a\Pinta\Pinta\Pinta.Gui.Widgets\Widgets\Layers\CellRendererSurface.cs:line 114
   at Pinta.Gui.Widgets.CellRendererSurface.OnRender(Context g, Widget widget, Rectangle background_area, Rectangle cell_area, CellRendererState flags) in D:\a\Pinta\Pinta\Pinta.Gui.Widgets\Widgets\Layers\CellRendererSurface.cs:line 69
   at Gtk.CellRenderer.Render_cb(IntPtr inst, IntPtr cr, IntPtr widget, IntPtr background_area, IntPtr cell_area, Int32 flags)

**Comment by cameronwhite** [comment]
That sounds like a separate issue from the original error you were describing?

**Comment by temginson** [comment]
nah it happend the same way
________________________________
Från: Cameron White ***@***.***>
Skickat: den 6 oktober 2023 07:18
Till: PintaProject/Pinta ***@***.***>
Kopia: temginson ***@***.***>; Author ***@***.***>
Ämne: Re: [PintaProject/Pinta] redo stack is empty (Issue #536)


That sounds like a separate issue from the original error you were describing?
