### ISSUE TITLE
cant save this

### ISSUE THREAD

**Issue by temginson** [PintaProject/Pinta#584]
**Description**
geet an error when trying to save a .png that had lots of layers saved

**To Reproduce**
idk 
**Additional Info**
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Pinta.Actions.SaveDocumentImplmentationAction.SaveFileAs(Document document) in D:\a\Pinta\Pinta\Pinta\Actions\File\SaveDocumentImplementationAction.cs:line 126
   at Pinta.Actions.SaveDocumentImplmentationAction.Activated(Object sender, DocumentCancelEventArgs e) in D:\a\Pinta\Pinta\Pinta\Actions\File\SaveDocumentImplementationAction.cs:line 56
   at Pinta.Core.FileActions.RaiseSaveDocument(Document document, Boolean saveAs) in D:\a\Pinta\Pinta\Pinta.Core\Actions\FileActions.cs:line 119
   at Pinta.Core.Document.Save(Boolean saveAs) in D:\a\Pinta\Pinta\Pinta.Core\Classes\Document.cs:line 394
   at Pinta.Actions.SaveDocumentAsAction.Activated(Object sender, EventArgs e) in D:\a\Pinta\Pinta\Pinta\Actions\File\SaveDocumentAsAction.cs:line 48
   at Pinta.Core.Command.<.ctor>b__33_0(Object o, ActivatedArgs args) in D:\a\Pinta\Pinta\Pinta.Core\Actions\Command.cs:line 61
   at InvokeStub_ActivatedHandler.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data) 

https://drive.google.com/file/d/10DhPCSYAKUJlr-a4si0s-P351jXwACkc/view?usp=sharing this is the file i have problem with

**Version**
Please include your operating system (e.g. Ubuntu 22.04) and which version of Pinta (e.g. 2.1) you are using.
windows 11 pro insider version 23h2

**Comment by cameronwhite** [comment]
I haven't been able to reproduce this yet, but I think it may be Windows-only judging by similar bug reports on Launchpad
Is there anything particular that seems to trigger this (e.g. the file name or directory you're saving to), or does it consistently happen with any image?

**Comment by cameronwhite** [comment]
I've made an attempt at fixing this based on the error message, but still haven't reproduced it.
Could you please try the latest build from https://github.com/PintaProject/Pinta/actions/runs/6859516946 (download link at the bottom - requires a GitHub login) and let me know if that resolved the error?

**Comment by temginson** [comment]
> I haven't been able to reproduce this yet, but I think it may be Windows-only judging by similar bug reports on Launchpad Is there anything particular that seems to trigger this (e.g. the file name or directory you're saving to), or does it consistently happen with any image?

i dont really know its like if i have it open and then let my computer go to sleep then i get that error

**Comment by cameronwhite** [comment]
OK thanks - please let me know if the newer build I linked to seems to resolve the issue!

**Comment by temginson** [comment]
> OK thanks - please let me know if the newer build I linked to seems to resolve the issue!

okay do i need to uninstall my current pinta?

**Comment by temginson** [comment]
sorry i havent had time to install this untill now but it just says that the app is unverified and  cant install it

**Comment by cameronwhite** [comment]
Hmm, isn't there usually an "Install anyways" type of option? (it might be hidden away under some toggle, unless you're perhaps doing this on a very locked-down system without admin permissions)

**Comment by temginson** [comment]
yeah its after that i get the error installer it just says that i should contact the developer and ask it if ther is a version for my device
________________________________
Från: Cameron White ***@***.***>
Skickat: den 21 november 2023 04:30
Till: PintaProject/Pinta ***@***.***>
Kopia: temginson ***@***.***>; Author ***@***.***>
Ämne: Re: [PintaProject/Pinta] cant save this (Issue #584)


Hmm, isn't there usually an "Install anyways" type of option? (it might be hidden away under some toggle, unless you're perhaps doing this on a very locked-down system without admin permissions)

**Comment by cameronwhite** [comment]
Could you paste the text of that message? I’m not entirely sure what’s
going on here - it shouldn’t be any different than how you installed the
regular Pinta 2.1 build from the main website

**Comment by temginson** [comment]
here is a scrennshare of what happend https://drive.google.com/file/d/1FQ6v7Znl4MkoV3VlW7xZMVs8kXkVD-Ee/view?usp=sharing

**Comment by cameronwhite** [comment]
Thanks. What's your operating system version, and is your CPU type anything other than x64 (e.g. 32-bit, or ARM?)
And, does the same issue happen if you're installing the regular Pinta build from the website?

**Comment by cameronwhite** [comment]
OK thanks, that sounds normal so I'm really not sure why that error message would appear. My only other idea would be to try running under any "Compatibility mode" options to see if that works

**Comment by iksi4prs** [comment]
@cameronwhite ,
I had same exception and stack trace for saving the simplest 2 layers file as .ora.
This was on Windows 11, with release "Pinta v# 2.1.1" (the latest available on downloads page)
Then found this issue when trying solve problem.
As you suggested, I tried the build here (although 2 months old):
https://github.com/PintaProject/Pinta/actions/runs/6859516946
And for me, it looks like solved the problem, saving works fine.

**Comment by cameronwhite** [comment]
Great, thank you for confirming!
