### ISSUE TITLE
Pinta crashed when I typed Chinese in text box.

### ISSUE THREAD

**Issue by Dangerise** [PintaProject/Pinta#722]
**Description**
As the title

**To Reproduce**
- Open a image
- Add a text
- Type chinese
- crash

**Additional Info**
![pinta](https://github.com/PintaProject/Pinta/assets/88434542/fcbb1ea4-63c6-4b75-a8fe-3ee5486a09b7)

**Version**
![image](https://github.com/PintaProject/Pinta/assets/88434542/28c66348-9ace-4faa-ba22-030aec6a38ec)

Pinta version : 2.1.1

**Comment by cameronwhite** [comment]
If you launch Pinta from the terminal, is there any crash log? A hard crash like that probably indicates an issue in the GTK libraries

**Comment by Dangerised** [comment]
@cameronwhite 
<details>
   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at Gtk.IMContext.Reset()

   at Pinta.Tools.TextTool.OnIMCommit(System.Object, Gtk.CommitArgs)

   at DynamicClass.InvokeStub_CommitHandler.Invoke(System.Object, System.Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)

   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)

   at System.Delegate.DynamicInvokeImpl(System.Object[])

   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)

   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)

   at GLib.Application.Run(System.String, System.String[])

   at Pinta.MainClass.Main(System.String[])

fish: Job 1, 'pinta > log' terminated by signal SIGABRT (Abort)


</details>

**Comment by cameronwhite** [comment]
Thanks, it looks like there is some infinite recursion where resetting the input method context triggers another commit of the text.

**Comment by vigorox** [comment]
Got the same issue on macOS. Inputting in Chinese or Japanese will make Pinta crashed immediately.

**Comment by cameronwhite** [comment]
Thanks, I could reproduce this on macOS with the Chinese input method.

@Dangerise - would you be able to test the latest `master` branch (commit 3b385de) to see if it also fixes the crash on your platform?

**Comment by Dangerise** [comment]
@cameronwhite seems to be fixed

**Comment by cameronwhite** [comment]
Great, thanks for confirming!
